#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TokyoChokoku.Patmark.Droid.Resource", IsApplication=true)]

namespace TokyoChokoku.Patmark.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int settings_menu = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int alpha = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int aspectRatio = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int barrierAllowsGoneWidgets = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int barrierDirection = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int chainUseRtl = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int constraintSet = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int constraint_referenced_ids = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int content = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int emptyVisibility = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int font = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int fontProviderAuthority = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int fontProviderCerts = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int fontProviderFetchStrategy = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int fontProviderFetchTimeout = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int fontProviderPackage = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int fontProviderQuery = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int fontStyle = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int fontVariationSettings = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int fontWeight = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int image = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int layout_aspectRatio = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int layout_constrainedHeight = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int layout_constrainedWidth = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int layout_constraintBaseline_creator = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int layout_constraintBaseline_toBaselineOf = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int layout_constraintBottom_creator = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int layout_constraintBottom_toBottomOf = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int layout_constraintBottom_toTopOf = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int layout_constraintCircle = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int layout_constraintCircleAngle = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int layout_constraintCircleRadius = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int layout_constraintDimensionRatio = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int layout_constraintEnd_toEndOf = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int layout_constraintEnd_toStartOf = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int layout_constraintGuide_begin = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int layout_constraintGuide_end = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int layout_constraintGuide_percent = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int layout_constraintHeight_default = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int layout_constraintHeight_max = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int layout_constraintHeight_min = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int layout_constraintHeight_percent = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int layout_constraintHorizontal_bias = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int layout_constraintHorizontal_chainStyle = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int layout_constraintHorizontal_weight = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int layout_constraintLeft_creator = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int layout_constraintLeft_toLeftOf = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int layout_constraintLeft_toRightOf = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int layout_constraintRight_creator = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int layout_constraintRight_toLeftOf = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int layout_constraintRight_toRightOf = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int layout_constraintStart_toEndOf = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int layout_constraintStart_toStartOf = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int layout_constraintTop_creator = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int layout_constraintTop_toBottomOf = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int layout_constraintTop_toTopOf = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int layout_constraintVertical_bias = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int layout_constraintVertical_chainStyle = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int layout_constraintVertical_weight = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public const int layout_constraintWidth_default = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public const int layout_constraintWidth_max = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int layout_constraintWidth_min = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int layout_constraintWidth_percent = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int layout_editor_absoluteX = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int layout_editor_absoluteY = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int layout_goneMarginBottom = 2130837568;
			
			// aapt resource value: 0x7F020041
			public const int layout_goneMarginEnd = 2130837569;
			
			// aapt resource value: 0x7F020042
			public const int layout_goneMarginLeft = 2130837570;
			
			// aapt resource value: 0x7F020043
			public const int layout_goneMarginRight = 2130837571;
			
			// aapt resource value: 0x7F020044
			public const int layout_goneMarginStart = 2130837572;
			
			// aapt resource value: 0x7F020045
			public const int layout_goneMarginTop = 2130837573;
			
			// aapt resource value: 0x7F020046
			public const int layout_heightPercent = 2130837574;
			
			// aapt resource value: 0x7F020047
			public const int layout_marginBottomPercent = 2130837575;
			
			// aapt resource value: 0x7F020048
			public const int layout_marginEndPercent = 2130837576;
			
			// aapt resource value: 0x7F020049
			public const int layout_marginLeftPercent = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public const int layout_marginPercent = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public const int layout_marginRightPercent = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public const int layout_marginStartPercent = 2130837580;
			
			// aapt resource value: 0x7F02004D
			public const int layout_marginTopPercent = 2130837581;
			
			// aapt resource value: 0x7F02004E
			public const int layout_optimizationLevel = 2130837582;
			
			// aapt resource value: 0x7F02004F
			public const int layout_widthPercent = 2130837583;
			
			// aapt resource value: 0x7F020050
			public const int maxHeightRate = 2130837584;
			
			// aapt resource value: 0x7F020051
			public const int maxWidthRate = 2130837585;
			
			// aapt resource value: 0x7F020052
			public const int sc_border_width = 2130837586;
			
			// aapt resource value: 0x7F020053
			public const int sc_checked_text_color = 2130837587;
			
			// aapt resource value: 0x7F020054
			public const int sc_corner_radius = 2130837588;
			
			// aapt resource value: 0x7F020055
			public const int sc_tint_color = 2130837589;
			
			// aapt resource value: 0x7F020056
			public const int ttcIndex = 2130837590;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int notification_action_color_filter = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int notification_icon_bg_color = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int patmark_main = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int patmark_sub = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int patmark_suppressed = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int radio_button_selected_color = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int radio_button_unselected_color = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int ripple_material_light = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int secondary_text_default_material_light = 2130903048;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int action_sheet_button_textsize = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int compat_button_inset_horizontal_material = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int compat_button_inset_vertical_material = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int compat_button_padding_horizontal_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int compat_button_padding_vertical_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int compat_control_corner_material = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int compat_notification_large_icon_max_height = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int compat_notification_large_icon_max_width = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int embossment_ui_height = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_action_icon_size = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_action_text_size = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_big_circle_margin = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notification_content_margin_start = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int notification_large_icon_height = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int notification_large_icon_width = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int notification_main_column_padding_top = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int notification_media_narrow_margin = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int notification_right_icon_size = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int notification_right_side_padding_top = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int notification_small_icon_background_padding = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int notification_small_icon_size_as_large = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int notification_subtext_size = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int notification_top_pad = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int notification_top_pad_large_text = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int radio_button_conner_radius = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int radio_button_stroke_border = 2130968601;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int actionsheet_button = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int button_border = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int button_text_color = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int notification_action_background = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int notification_bg = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int notification_bg_low = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int notification_bg_low_normal = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int notification_bg_low_pressed = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int notification_bg_normal = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int notification_bg_normal_pressed = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int notification_icon_background = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notification_template_icon_bg = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int notification_template_icon_low_bg = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int notification_tile_bg = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int notify_panel_notification_icon_bg = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int patmark_button_forward = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int patmark_button_previous = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int patmark_button_send = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int patmark_gray_forward = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int patmark_gray_previous = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int patmark_gray_send = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int patmark_orange_force_medium = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int patmark_orange_force_strong = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int patmark_orange_force_weak = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int patmark_orange_forward = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int patmark_orange_previous = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int patmark_orange_quality_dot = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int patmark_orange_quality_line = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int patmark_orange_quality_medium = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int patmark_orange_send = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int patmark_orange_text_large = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int patmark_orange_text_medium = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int patmark_orange_text_small = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int patmark_segment_force_medium = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int patmark_segment_force_strong = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int patmark_segment_force_weak = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int patmark_segment_quality_dot = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int patmark_segment_quality_line = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int patmark_segment_quality_medium = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int patmark_segment_text_large = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int patmark_segment_text_medium = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int patmark_segment_text_small = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int patmark_white_force_medium = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int patmark_white_force_strong = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int patmark_white_force_weak = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int patmark_white_forward = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int patmark_white_previous = 2131034158;
			
			// aapt resource value: 0x7F05002F
			public const int patmark_white_quality_dot = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int patmark_white_quality_line = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int patmark_white_quality_medium = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int patmark_white_text_large = 2131034162;
			
			// aapt resource value: 0x7F050033
			public const int patmark_white_text_medium = 2131034163;
			
			// aapt resource value: 0x7F050034
			public const int patmark_white_text_small = 2131034164;
			
			// aapt resource value: 0x7F050035
			public const int radio_checked = 2131034165;
			
			// aapt resource value: 0x7F050036
			public const int radio_unchecked = 2131034166;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060005
			public const int actions = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int actionsheet_clear = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int actionsheet_rename = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int actionsheet_replace = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int actionsheet_retrieve = 2131099657;
			
			// aapt resource value: 0x7F060001
			public const int action_container = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int action_divider = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int action_image = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int action_text = 2131099652;
			
			// aapt resource value: 0x7F06000A
			public const int async = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int barrier = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int blankBetweenPageChangers = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int blocking = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int bottom = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int bottom_ui_area_group = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int buttonSave = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int button_pageBack = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int button_pageForward = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int button_send = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int button_send_at_field_list = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int chains = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int chronometer = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int clear_button = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int dimensions = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int direct = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int edittext_on_field_editor = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int embossment_field_list_ui = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int embossment_preview_ui = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int embossment_ui_frame = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int end = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int fieldPreview = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int fieldPreview__ = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int field_list = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int field_list_area_frame = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int files_button = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int forceLabel = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int forever = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int gone = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int icon = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int icon_group = 2131099688;
			
			// aapt resource value: 0x7F06002F
			public const int includedEmbossmentFieldListUI = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int includedFieldListArea = 2131099696;
			
			// aapt resource value: 0x7F060029
			public const int includeEmbossmentPreviewUI = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int includeEmbossmentUI = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int includeForceUI = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int includePreviewArea = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int includeQualityUI = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int includeTextSizeUI = 2131099694;
			
			// aapt resource value: 0x7F060031
			public const int info = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int invisible = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int italic = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int label_currentPage = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int label_pageCountSeparator = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int label_totalPage = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int left = 2131099703;
			
			// aapt resource value: 0x7F060038
			public const int line1 = 2131099704;
			
			// aapt resource value: 0x7F060039
			public const int line3 = 2131099705;
			
			// aapt resource value: 0x7F06003A
			public const int listView_fileCategory = 2131099706;
			
			// aapt resource value: 0x7F06003B
			public const int listView_fileList = 2131099707;
			
			// aapt resource value: 0x7F06003C
			public const int menuButton_add = 2131099708;
			
			// aapt resource value: 0x7F06003D
			public const int menuButton_reload = 2131099709;
			
			// aapt resource value: 0x7F06003E
			public const int menu_buttons = 2131099710;
			
			// aapt resource value: 0x7F06003F
			public const int middle_area_group = 2131099711;
			
			// aapt resource value: 0x7F060040
			public const int myButton = 2131099712;
			
			// aapt resource value: 0x7F060041
			public const int next_on_field_editor = 2131099713;
			
			// aapt resource value: 0x7F060042
			public const int none = 2131099714;
			
			// aapt resource value: 0x7F060043
			public const int normal = 2131099715;
			
			// aapt resource value: 0x7F060044
			public const int notification_background = 2131099716;
			
			// aapt resource value: 0x7F060045
			public const int notification_main_column = 2131099717;
			
			// aapt resource value: 0x7F060046
			public const int notification_main_column_container = 2131099718;
			
			// aapt resource value: 0x7F060047
			public const int packed = 2131099719;
			
			// aapt resource value: 0x7F060048
			public const int parent = 2131099720;
			
			// aapt resource value: 0x7F060049
			public const int percent = 2131099721;
			
			// aapt resource value: 0x7F06004A
			public const int previewAreaFrame = 2131099722;
			
			// aapt resource value: 0x7F06004B
			public const int preview_area_group = 2131099723;
			
			// aapt resource value: 0x7F06004C
			public const int preview_bottom_limit_guideline = 2131099724;
			
			// aapt resource value: 0x7F06004D
			public const int preview_ui_area_group = 2131099725;
			
			// aapt resource value: 0x7F06004E
			public const int progressBar = 2131099726;
			
			// aapt resource value: 0x7F06004F
			public const int progressBarView = 2131099727;
			
			// aapt resource value: 0x7F060000
			public const int ProgressDialogPrompt = 2131099648;
			
			// aapt resource value: 0x7F060050
			public const int qualityLabel = 2131099728;
			
			// aapt resource value: 0x7F060051
			public const int right = 2131099729;
			
			// aapt resource value: 0x7F060052
			public const int right_icon = 2131099730;
			
			// aapt resource value: 0x7F060053
			public const int right_side = 2131099731;
			
			// aapt resource value: 0x7F060054
			public const int rulerView = 2131099732;
			
			// aapt resource value: 0x7F060055
			public const int rulerView__ = 2131099733;
			
			// aapt resource value: 0x7F060056
			public const int saveAsDialog_textField = 2131099734;
			
			// aapt resource value: 0x7F060057
			public const int segment = 2131099735;
			
			// aapt resource value: 0x7F060058
			public const int segmentOf_dot = 2131099736;
			
			// aapt resource value: 0x7F060059
			public const int segmentOf_large = 2131099737;
			
			// aapt resource value: 0x7F06005A
			public const int segmentOf_line = 2131099738;
			
			// aapt resource value: 0x7F06005B
			public const int segmentOf_medium = 2131099739;
			
			// aapt resource value: 0x7F06005C
			public const int segmentOf_small = 2131099740;
			
			// aapt resource value: 0x7F06005D
			public const int segmentOf_strong = 2131099741;
			
			// aapt resource value: 0x7F06005E
			public const int segmentOf_weak = 2131099742;
			
			// aapt resource value: 0x7F06005F
			public const int settings_button = 2131099743;
			
			// aapt resource value: 0x7F060060
			public const int settings_menu = 2131099744;
			
			// aapt resource value: 0x7F060061
			public const int spinner_force_medium = 2131099745;
			
			// aapt resource value: 0x7F060062
			public const int spinner_force_strong = 2131099746;
			
			// aapt resource value: 0x7F060063
			public const int spinner_force_weak = 2131099747;
			
			// aapt resource value: 0x7F060064
			public const int spinner_quality_dot = 2131099748;
			
			// aapt resource value: 0x7F060065
			public const int spinner_quality_line = 2131099749;
			
			// aapt resource value: 0x7F060066
			public const int spinner_quality_medium = 2131099750;
			
			// aapt resource value: 0x7F060067
			public const int spinner_text_size_large = 2131099751;
			
			// aapt resource value: 0x7F060068
			public const int spinner_text_size_medium = 2131099752;
			
			// aapt resource value: 0x7F060069
			public const int spinner_text_size_small = 2131099753;
			
			// aapt resource value: 0x7F06006A
			public const int spread = 2131099754;
			
			// aapt resource value: 0x7F06006B
			public const int spread_inside = 2131099755;
			
			// aapt resource value: 0x7F06006C
			public const int standard = 2131099756;
			
			// aapt resource value: 0x7F06006D
			public const int start = 2131099757;
			
			// aapt resource value: 0x7F06006E
			public const int tab_top_guideline = 2131099758;
			
			// aapt resource value: 0x7F06006F
			public const int tag_transition_group = 2131099759;
			
			// aapt resource value: 0x7F060070
			public const int tag_unhandled_key_event_manager = 2131099760;
			
			// aapt resource value: 0x7F060071
			public const int tag_unhandled_key_listeners = 2131099761;
			
			// aapt resource value: 0x7F060072
			public const int text = 2131099762;
			
			// aapt resource value: 0x7F060073
			public const int text2 = 2131099763;
			
			// aapt resource value: 0x7F060074
			public const int textSizeLabel = 2131099764;
			
			// aapt resource value: 0x7F060075
			public const int time = 2131099765;
			
			// aapt resource value: 0x7F060076
			public const int title = 2131099766;
			
			// aapt resource value: 0x7F060077
			public const int top = 2131099767;
			
			// aapt resource value: 0x7F060078
			public const int wifi_button = 2131099768;
			
			// aapt resource value: 0x7F060079
			public const int wrap = 2131099769;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public const int status_bar_notification_info_maxnum = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int DefaultMarkingParameter = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int Embossment = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int EmbossmentFieldListUI = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int EmbossmentPreviewUI = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int EmbossmentUI = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int FieldEditor = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int FieldList = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int FileActionList = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int FileCategorySelection = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int FileMenu = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int ForceSegment = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int LoadingOverlay = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int Main = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int notification_action = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int notification_action_tombstone = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int notification_template_custom_big = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int notification_template_icon_group = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int notification_template_part_chronometer = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int notification_template_part_time = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int PreviewArea = 2131230739;
			
			// aapt resource value: 0x7F080014
			public const int ProgressDialog = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int QualitySegment = 2131230741;
			
			// aapt resource value: 0x7F080016
			public const int RemoteFileActionList = 2131230742;
			
			// aapt resource value: 0x7F080017
			public const int SaveAsDialog = 2131230743;
			
			// aapt resource value: 0x7F080018
			public const int Settings = 2131230744;
			
			// aapt resource value: 0x7F080019
			public const int TextSizeSegment = 2131230745;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F090000
			public const int DefaultMarkingParameterMenu = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int FileAddMenu = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int RemoteReloadMenu = 2131296258;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F0A0000
			public const int icon = 2131361792;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0B0011
			public const int apply = 2131427345;
			
			// aapt resource value: 0x7F0B0010
			public const int app_name = 2131427344;
			
			// aapt resource value: 0x7F0B0012
			public const int cancel = 2131427346;
			
			// aapt resource value: 0x7F0B0013
			public const int defaultMarkingParameterActivity_name = 2131427347;
			
			// aapt resource value: 0x7F0B0014
			public const int embossmentActivity_name = 2131427348;
			
			// aapt resource value: 0x7F0B0015
			public const int fieldEditorActivity_name = 2131427349;
			
			// aapt resource value: 0x7F0B0000
			public const int FieldTypeName_Bypass = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int FieldTypeName_Circle = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int FieldTypeName_DataMatrix = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int FieldTypeName_Ellipse = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int FieldTypeName_InnerArcText = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int FieldTypeName_Line = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int FieldTypeName_OuterArcText = 2131427334;
			
			// aapt resource value: 0x7F0B0007
			public const int FieldTypeName_QrCode = 2131427335;
			
			// aapt resource value: 0x7F0B0008
			public const int FieldTypeName_Rectangle = 2131427336;
			
			// aapt resource value: 0x7F0B0009
			public const int FieldTypeName_Text = 2131427337;
			
			// aapt resource value: 0x7F0B000A
			public const int FieldTypeName_Triangle = 2131427338;
			
			// aapt resource value: 0x7F0B000B
			public const int FieldTypeName_Unknown = 2131427339;
			
			// aapt resource value: 0x7F0B000C
			public const int FieldTypeName_XVerticalText = 2131427340;
			
			// aapt resource value: 0x7F0B000D
			public const int FieldTypeName_YVerticalText = 2131427341;
			
			// aapt resource value: 0x7F0B0016
			public const int fileCategorySelectionActivity_name = 2131427350;
			
			// aapt resource value: 0x7F0B0017
			public const int file_source_label_latest = 2131427351;
			
			// aapt resource value: 0x7F0B0018
			public const int file_source_label_local = 2131427352;
			
			// aapt resource value: 0x7F0B0019
			public const int file_source_label_remote = 2131427353;
			
			// aapt resource value: 0x7F0B001A
			public const int fit = 2131427354;
			
			// aapt resource value: 0x7F0B001B
			public const int hint_saveas_textField = 2131427355;
			
			// aapt resource value: 0x7F0B001C
			public const int ignore = 2131427356;
			
			// aapt resource value: 0x7F0B001D
			public const int label_changeOfMachineModel = 2131427357;
			
			// aapt resource value: 0x7F0B001E
			public const int label_clear = 2131427358;
			
			// aapt resource value: 0x7F0B001F
			public const int label_clear_preview_file = 2131427359;
			
			// aapt resource value: 0x7F0B0020
			public const int label_doYouChangeMachineModel = 2131427360;
			
			// aapt resource value: 0x7F0B0024
			public const int label_files = 2131427364;
			
			// aapt resource value: 0x7F0B0021
			public const int label_file_menu_latest = 2131427361;
			
			// aapt resource value: 0x7F0B0022
			public const int label_file_menu_local = 2131427362;
			
			// aapt resource value: 0x7F0B0023
			public const int label_file_menu_remote = 2131427363;
			
			// aapt resource value: 0x7F0B0025
			public const int label_force = 2131427365;
			
			// aapt resource value: 0x7F0B0026
			public const int label_machine_model_no_message = 2131427366;
			
			// aapt resource value: 0x7F0B0027
			public const int label_machine_model_no_title = 2131427367;
			
			// aapt resource value: 0x7F0B0028
			public const int label_quality = 2131427368;
			
			// aapt resource value: 0x7F0B0029
			public const int label_reload = 2131427369;
			
			// aapt resource value: 0x7F0B002A
			public const int label_rename = 2131427370;
			
			// aapt resource value: 0x7F0B002B
			public const int label_replace = 2131427371;
			
			// aapt resource value: 0x7F0B002C
			public const int label_retrieve = 2131427372;
			
			// aapt resource value: 0x7F0B002E
			public const int label_saveas = 2131427374;
			
			// aapt resource value: 0x7F0B002D
			public const int label_saveOverCheck = 2131427373;
			
			// aapt resource value: 0x7F0B002F
			public const int label_settings = 2131427375;
			
			// aapt resource value: 0x7F0B0030
			public const int label_textSize = 2131427376;
			
			// aapt resource value: 0x7F0B0031
			public const int label_wifi = 2131427377;
			
			// aapt resource value: 0x7F0B0032
			public const int localFileMenuActivity_name = 2131427378;
			
			// aapt resource value: 0x7F0B0033
			public const int message_editName = 2131427379;
			
			// aapt resource value: 0x7F0B0035
			public const int message_saveas = 2131427381;
			
			// aapt resource value: 0x7F0B0034
			public const int message_saveOverCheck = 2131427380;
			
			// aapt resource value: 0x7F0B0036
			public const int msg_serialField_writeFileSelectorLocal = 2131427382;
			
			// aapt resource value: 0x7F0B0037
			public const int overlay_now_processing = 2131427383;
			
			// aapt resource value: 0x7F0B0038
			public const int patmark_15x15 = 2131427384;
			
			// aapt resource value: 0x7F0B0039
			public const int patmark_33x15 = 2131427385;
			
			// aapt resource value: 0x7F0B003A
			public const int patmark_80x20 = 2131427386;
			
			// aapt resource value: 0x7F0B003B
			public const int remoteFileMenuActivity_name = 2131427387;
			
			// aapt resource value: 0x7F0B000E
			public const int RemoteFileMenuDialogManager_ErrorMessage = 2131427342;
			
			// aapt resource value: 0x7F0B000F
			public const int RemoteFileMenuDialogManager_Space = 2131427343;
			
			// aapt resource value: 0x7F0B003C
			public const int save = 2131427388;
			
			// aapt resource value: 0x7F0B003D
			public const int settingsActivity_name = 2131427389;
			
			// aapt resource value: 0x7F0B003E
			public const int status_bar_notification_info_overflow = 2131427390;
			
			// aapt resource value: 0x7F0B003F
			public const int toast_advance_mode_file_can_not_be_edited = 2131427391;
			
			// aapt resource value: 0x7F0B0040
			public const int toast_appsetting_controller_different = 2131427392;
			
			// aapt resource value: 0x7F0B0041
			public const int toast_appsetting_controller_fail_to_check = 2131427393;
			
			// aapt resource value: 0x7F0B0042
			public const int toast_appsetting_controller_fail_to_hold = 2131427394;
			
			// aapt resource value: 0x7F0B0043
			public const int toast_cleared = 2131427395;
			
			// aapt resource value: 0x7F0B0044
			public const int toast_communication_excluded_me = 2131427396;
			
			// aapt resource value: 0x7F0B0045
			public const int toast_communication_protected = 2131427397;
			
			// aapt resource value: 0x7F0B0046
			public const int toast_communication_required = 2131427398;
			
			// aapt resource value: 0x7F0B0047
			public const int toast_communication_started = 2131427399;
			
			// aapt resource value: 0x7F0B0048
			public const int toast_communication_terminated = 2131427400;
			
			// aapt resource value: 0x7F0B0049
			public const int toast_communication_timed_out = 2131427401;
			
			// aapt resource value: 0x7F0B004A
			public const int toast_current_file_cleared = 2131427402;
			
			// aapt resource value: 0x7F0B004B
			public const int toast_edited = 2131427403;
			
			// aapt resource value: 0x7F0B004C
			public const int toast_failed_to_clear = 2131427404;
			
			// aapt resource value: 0x7F0B004D
			public const int toast_failed_to_edit = 2131427405;
			
			// aapt resource value: 0x7F0B004E
			public const int toast_failed_to_read = 2131427406;
			
			// aapt resource value: 0x7F0B004F
			public const int toast_failed_to_save = 2131427407;
			
			// aapt resource value: 0x7F0B0050
			public const int toast_failed_to_send_marking_file = 2131427408;
			
			// aapt resource value: 0x7F0B0051
			public const int toast_file_is_empty = 2131427409;
			
			// aapt resource value: 0x7F0B0052
			public const int toast_font_error = 2131427410;
			
			// aapt resource value: 0x7F0B0053
			public const int toast_invalidFileName = 2131427411;
			
			// aapt resource value: 0x7F0B0054
			public const int toast_marking_file_is_empty = 2131427412;
			
			// aapt resource value: 0x7F0B0055
			public const int toast_read = 2131427413;
			
			// aapt resource value: 0x7F0B0056
			public const int toast_ready_to_mark = 2131427414;
			
			// aapt resource value: 0x7F0B0057
			public const int toast_saved = 2131427415;
			
			// aapt resource value: 0x7F0B0058
			public const int toast_send_protected = 2131427416;
			
			// aapt resource value: 0x7F0B0059
			public const int toast_validation_on_text_sizes_too_large = 2131427417;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0C0000
			public const int AppTheme = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int DefaultMarkingParameterSettingsImage = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int DefaultMarkingParameterSettingsRow = 2131492866;
			
			// aapt resource value: 0x7F0C0003
			public const int DefaultMarkingParameterSettingsSpinner = 2131492867;
			
			// aapt resource value: 0x7F0C0004
			public const int RadioButton = 2131492868;
			
			// aapt resource value: 0x7F0C0005
			public const int TextAppearance_Compat_Notification = 2131492869;
			
			// aapt resource value: 0x7F0C0006
			public const int TextAppearance_Compat_Notification_Info = 2131492870;
			
			// aapt resource value: 0x7F0C0007
			public const int TextAppearance_Compat_Notification_Line2 = 2131492871;
			
			// aapt resource value: 0x7F0C0008
			public const int TextAppearance_Compat_Notification_Time = 2131492872;
			
			// aapt resource value: 0x7F0C0009
			public const int TextAppearance_Compat_Notification_Title = 2131492873;
			
			// aapt resource value: 0x7F0C000A
			public const int Widget_Compat_NotificationActionContainer = 2131492874;
			
			// aapt resource value: 0x7F0C000B
			public const int Widget_Compat_NotificationActionText = 2131492875;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F020000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130837504};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x10100C4,0x101011F,0x1010120,0x101013F,0x1010140,0x7F020002,0x7F020003,0x7F020004,0x7F020005,0x7F020006,0x7F020015,0x7F020016,0x7F020017,0x7F020018,0x7F020019,0x7F02001A,0x7F02001B,0x7F02001C,0x7F02001D,0x7F02001E,0x7F02001F,0x7F020020,0x7F020021,0x7F020022,0x7F020023,0x7F020024,0x7F020025,0x7F020026,0x7F020027,0x7F020028,0x7F020029,0x7F02002A,0x7F02002B,0x7F02002C,0x7F02002D,0x7F02002E,0x7F02002F,0x7F020030,0x7F020031,0x7F020032,0x7F020033,0x7F020034,0x7F020035,0x7F020036,0x7F020037,0x7F020038,0x7F020039,0x7F02003A,0x7F02003B,0x7F02003C,0x7F02003D,0x7F02003E,0x7F02003F,0x7F020040,0x7F020041,0x7F020042,0x7F020043,0x7F020044,0x7F020045,0x7F02004E }
			public static int[] ConstraintLayout_Layout = new int[] {
					16842948,
					16843039,
					16843040,
					16843071,
					16843072,
					2130837506,
					2130837507,
					2130837508,
					2130837509,
					2130837510,
					2130837525,
					2130837526,
					2130837527,
					2130837528,
					2130837529,
					2130837530,
					2130837531,
					2130837532,
					2130837533,
					2130837534,
					2130837535,
					2130837536,
					2130837537,
					2130837538,
					2130837539,
					2130837540,
					2130837541,
					2130837542,
					2130837543,
					2130837544,
					2130837545,
					2130837546,
					2130837547,
					2130837548,
					2130837549,
					2130837550,
					2130837551,
					2130837552,
					2130837553,
					2130837554,
					2130837555,
					2130837556,
					2130837557,
					2130837558,
					2130837559,
					2130837560,
					2130837561,
					2130837562,
					2130837563,
					2130837564,
					2130837565,
					2130837566,
					2130837567,
					2130837568,
					2130837569,
					2130837570,
					2130837571,
					2130837572,
					2130837573,
					2130837582};
			
			// aapt resource value: 2
			public const int ConstraintLayout_Layout_android_maxHeight = 2;
			
			// aapt resource value: 1
			public const int ConstraintLayout_Layout_android_maxWidth = 1;
			
			// aapt resource value: 4
			public const int ConstraintLayout_Layout_android_minHeight = 4;
			
			// aapt resource value: 3
			public const int ConstraintLayout_Layout_android_minWidth = 3;
			
			// aapt resource value: 0
			public const int ConstraintLayout_Layout_android_orientation = 0;
			
			// aapt resource value: 5
			public const int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
			
			// aapt resource value: 6
			public const int ConstraintLayout_Layout_barrierDirection = 6;
			
			// aapt resource value: 7
			public const int ConstraintLayout_Layout_chainUseRtl = 7;
			
			// aapt resource value: 8
			public const int ConstraintLayout_Layout_constraintSet = 8;
			
			// aapt resource value: 9
			public const int ConstraintLayout_Layout_constraint_referenced_ids = 9;
			
			// aapt resource value: 10
			public const int ConstraintLayout_Layout_layout_constrainedHeight = 10;
			
			// aapt resource value: 11
			public const int ConstraintLayout_Layout_layout_constrainedWidth = 11;
			
			// aapt resource value: 12
			public const int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
			
			// aapt resource value: 13
			public const int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
			
			// aapt resource value: 14
			public const int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
			
			// aapt resource value: 15
			public const int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
			
			// aapt resource value: 16
			public const int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
			
			// aapt resource value: 17
			public const int ConstraintLayout_Layout_layout_constraintCircle = 17;
			
			// aapt resource value: 18
			public const int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
			
			// aapt resource value: 19
			public const int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
			
			// aapt resource value: 20
			public const int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
			
			// aapt resource value: 21
			public const int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
			
			// aapt resource value: 22
			public const int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
			
			// aapt resource value: 23
			public const int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
			
			// aapt resource value: 24
			public const int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
			
			// aapt resource value: 25
			public const int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
			
			// aapt resource value: 26
			public const int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
			
			// aapt resource value: 27
			public const int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
			
			// aapt resource value: 28
			public const int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
			
			// aapt resource value: 29
			public const int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
			
			// aapt resource value: 30
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
			
			// aapt resource value: 31
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
			
			// aapt resource value: 32
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
			
			// aapt resource value: 33
			public const int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
			
			// aapt resource value: 34
			public const int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
			
			// aapt resource value: 37
			public const int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
			
			// aapt resource value: 38
			public const int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
			
			// aapt resource value: 39
			public const int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
			
			// aapt resource value: 40
			public const int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
			
			// aapt resource value: 41
			public const int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
			
			// aapt resource value: 42
			public const int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
			
			// aapt resource value: 43
			public const int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
			
			// aapt resource value: 44
			public const int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
			
			// aapt resource value: 45
			public const int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
			
			// aapt resource value: 46
			public const int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
			
			// aapt resource value: 47
			public const int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
			
			// aapt resource value: 48
			public const int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
			
			// aapt resource value: 49
			public const int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
			
			// aapt resource value: 50
			public const int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
			
			// aapt resource value: 51
			public const int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
			
			// aapt resource value: 52
			public const int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
			
			// aapt resource value: 53
			public const int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
			
			// aapt resource value: 54
			public const int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
			
			// aapt resource value: 55
			public const int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
			
			// aapt resource value: 56
			public const int ConstraintLayout_Layout_layout_goneMarginRight = 56;
			
			// aapt resource value: 57
			public const int ConstraintLayout_Layout_layout_goneMarginStart = 57;
			
			// aapt resource value: 58
			public const int ConstraintLayout_Layout_layout_goneMarginTop = 58;
			
			// aapt resource value: 59
			public const int ConstraintLayout_Layout_layout_optimizationLevel = 59;
			
			// aapt resource value: { 0x7F020007,0x7F020008 }
			public static int[] ConstraintLayout_placeholder = new int[] {
					2130837511,
					2130837512};
			
			// aapt resource value: 0
			public const int ConstraintLayout_placeholder_content = 0;
			
			// aapt resource value: 1
			public const int ConstraintLayout_placeholder_emptyVisibility = 1;
			
			// aapt resource value: { 0x10100C4,0x10100D0,0x10100DC,0x10100F4,0x10100F5,0x10100F7,0x10100F8,0x10100F9,0x10100FA,0x101031F,0x1010320,0x1010321,0x1010322,0x1010323,0x1010324,0x1010325,0x1010326,0x1010327,0x1010328,0x10103B5,0x10103B6,0x10103FA,0x1010440,0x7F020015,0x7F020016,0x7F020017,0x7F020018,0x7F020019,0x7F02001A,0x7F02001B,0x7F02001C,0x7F02001D,0x7F02001E,0x7F02001F,0x7F020020,0x7F020021,0x7F020022,0x7F020023,0x7F020024,0x7F020025,0x7F020026,0x7F020027,0x7F020028,0x7F020029,0x7F02002A,0x7F02002B,0x7F02002C,0x7F02002D,0x7F02002E,0x7F02002F,0x7F020030,0x7F020031,0x7F020032,0x7F020033,0x7F020034,0x7F020035,0x7F020036,0x7F020037,0x7F020038,0x7F020039,0x7F02003A,0x7F02003B,0x7F02003C,0x7F02003D,0x7F02003E,0x7F02003F,0x7F020040,0x7F020041,0x7F020042,0x7F020043,0x7F020044,0x7F020045 }
			public static int[] ConstraintSet = new int[] {
					16842948,
					16842960,
					16842972,
					16842996,
					16842997,
					16842999,
					16843000,
					16843001,
					16843002,
					16843551,
					16843552,
					16843553,
					16843554,
					16843555,
					16843556,
					16843557,
					16843558,
					16843559,
					16843560,
					16843701,
					16843702,
					16843770,
					16843840,
					2130837525,
					2130837526,
					2130837527,
					2130837528,
					2130837529,
					2130837530,
					2130837531,
					2130837532,
					2130837533,
					2130837534,
					2130837535,
					2130837536,
					2130837537,
					2130837538,
					2130837539,
					2130837540,
					2130837541,
					2130837542,
					2130837543,
					2130837544,
					2130837545,
					2130837546,
					2130837547,
					2130837548,
					2130837549,
					2130837550,
					2130837551,
					2130837552,
					2130837553,
					2130837554,
					2130837555,
					2130837556,
					2130837557,
					2130837558,
					2130837559,
					2130837560,
					2130837561,
					2130837562,
					2130837563,
					2130837564,
					2130837565,
					2130837566,
					2130837567,
					2130837568,
					2130837569,
					2130837570,
					2130837571,
					2130837572,
					2130837573};
			
			// aapt resource value: 9
			public const int ConstraintSet_android_alpha = 9;
			
			// aapt resource value: 22
			public const int ConstraintSet_android_elevation = 22;
			
			// aapt resource value: 1
			public const int ConstraintSet_android_id = 1;
			
			// aapt resource value: 4
			public const int ConstraintSet_android_layout_height = 4;
			
			// aapt resource value: 8
			public const int ConstraintSet_android_layout_marginBottom = 8;
			
			// aapt resource value: 20
			public const int ConstraintSet_android_layout_marginEnd = 20;
			
			// aapt resource value: 5
			public const int ConstraintSet_android_layout_marginLeft = 5;
			
			// aapt resource value: 7
			public const int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 19
			public const int ConstraintSet_android_layout_marginStart = 19;
			
			// aapt resource value: 6
			public const int ConstraintSet_android_layout_marginTop = 6;
			
			// aapt resource value: 3
			public const int ConstraintSet_android_layout_width = 3;
			
			// aapt resource value: 0
			public const int ConstraintSet_android_orientation = 0;
			
			// aapt resource value: 16
			public const int ConstraintSet_android_rotation = 16;
			
			// aapt resource value: 17
			public const int ConstraintSet_android_rotationX = 17;
			
			// aapt resource value: 18
			public const int ConstraintSet_android_rotationY = 18;
			
			// aapt resource value: 14
			public const int ConstraintSet_android_scaleX = 14;
			
			// aapt resource value: 15
			public const int ConstraintSet_android_scaleY = 15;
			
			// aapt resource value: 10
			public const int ConstraintSet_android_transformPivotX = 10;
			
			// aapt resource value: 11
			public const int ConstraintSet_android_transformPivotY = 11;
			
			// aapt resource value: 12
			public const int ConstraintSet_android_translationX = 12;
			
			// aapt resource value: 13
			public const int ConstraintSet_android_translationY = 13;
			
			// aapt resource value: 21
			public const int ConstraintSet_android_translationZ = 21;
			
			// aapt resource value: 2
			public const int ConstraintSet_android_visibility = 2;
			
			// aapt resource value: 23
			public const int ConstraintSet_layout_constrainedHeight = 23;
			
			// aapt resource value: 24
			public const int ConstraintSet_layout_constrainedWidth = 24;
			
			// aapt resource value: 25
			public const int ConstraintSet_layout_constraintBaseline_creator = 25;
			
			// aapt resource value: 26
			public const int ConstraintSet_layout_constraintBaseline_toBaselineOf = 26;
			
			// aapt resource value: 27
			public const int ConstraintSet_layout_constraintBottom_creator = 27;
			
			// aapt resource value: 28
			public const int ConstraintSet_layout_constraintBottom_toBottomOf = 28;
			
			// aapt resource value: 29
			public const int ConstraintSet_layout_constraintBottom_toTopOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintSet_layout_constraintCircle = 30;
			
			// aapt resource value: 31
			public const int ConstraintSet_layout_constraintCircleAngle = 31;
			
			// aapt resource value: 32
			public const int ConstraintSet_layout_constraintCircleRadius = 32;
			
			// aapt resource value: 33
			public const int ConstraintSet_layout_constraintDimensionRatio = 33;
			
			// aapt resource value: 34
			public const int ConstraintSet_layout_constraintEnd_toEndOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintSet_layout_constraintEnd_toStartOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintSet_layout_constraintGuide_begin = 36;
			
			// aapt resource value: 37
			public const int ConstraintSet_layout_constraintGuide_end = 37;
			
			// aapt resource value: 38
			public const int ConstraintSet_layout_constraintGuide_percent = 38;
			
			// aapt resource value: 39
			public const int ConstraintSet_layout_constraintHeight_default = 39;
			
			// aapt resource value: 40
			public const int ConstraintSet_layout_constraintHeight_max = 40;
			
			// aapt resource value: 41
			public const int ConstraintSet_layout_constraintHeight_min = 41;
			
			// aapt resource value: 42
			public const int ConstraintSet_layout_constraintHeight_percent = 42;
			
			// aapt resource value: 43
			public const int ConstraintSet_layout_constraintHorizontal_bias = 43;
			
			// aapt resource value: 44
			public const int ConstraintSet_layout_constraintHorizontal_chainStyle = 44;
			
			// aapt resource value: 45
			public const int ConstraintSet_layout_constraintHorizontal_weight = 45;
			
			// aapt resource value: 46
			public const int ConstraintSet_layout_constraintLeft_creator = 46;
			
			// aapt resource value: 47
			public const int ConstraintSet_layout_constraintLeft_toLeftOf = 47;
			
			// aapt resource value: 48
			public const int ConstraintSet_layout_constraintLeft_toRightOf = 48;
			
			// aapt resource value: 49
			public const int ConstraintSet_layout_constraintRight_creator = 49;
			
			// aapt resource value: 50
			public const int ConstraintSet_layout_constraintRight_toLeftOf = 50;
			
			// aapt resource value: 51
			public const int ConstraintSet_layout_constraintRight_toRightOf = 51;
			
			// aapt resource value: 52
			public const int ConstraintSet_layout_constraintStart_toEndOf = 52;
			
			// aapt resource value: 53
			public const int ConstraintSet_layout_constraintStart_toStartOf = 53;
			
			// aapt resource value: 54
			public const int ConstraintSet_layout_constraintTop_creator = 54;
			
			// aapt resource value: 55
			public const int ConstraintSet_layout_constraintTop_toBottomOf = 55;
			
			// aapt resource value: 56
			public const int ConstraintSet_layout_constraintTop_toTopOf = 56;
			
			// aapt resource value: 57
			public const int ConstraintSet_layout_constraintVertical_bias = 57;
			
			// aapt resource value: 58
			public const int ConstraintSet_layout_constraintVertical_chainStyle = 58;
			
			// aapt resource value: 59
			public const int ConstraintSet_layout_constraintVertical_weight = 59;
			
			// aapt resource value: 60
			public const int ConstraintSet_layout_constraintWidth_default = 60;
			
			// aapt resource value: 61
			public const int ConstraintSet_layout_constraintWidth_max = 61;
			
			// aapt resource value: 62
			public const int ConstraintSet_layout_constraintWidth_min = 62;
			
			// aapt resource value: 63
			public const int ConstraintSet_layout_constraintWidth_percent = 63;
			
			// aapt resource value: 64
			public const int ConstraintSet_layout_editor_absoluteX = 64;
			
			// aapt resource value: 65
			public const int ConstraintSet_layout_editor_absoluteY = 65;
			
			// aapt resource value: 66
			public const int ConstraintSet_layout_goneMarginBottom = 66;
			
			// aapt resource value: 67
			public const int ConstraintSet_layout_goneMarginEnd = 67;
			
			// aapt resource value: 68
			public const int ConstraintSet_layout_goneMarginLeft = 68;
			
			// aapt resource value: 69
			public const int ConstraintSet_layout_goneMarginRight = 69;
			
			// aapt resource value: 70
			public const int ConstraintSet_layout_goneMarginStart = 70;
			
			// aapt resource value: 71
			public const int ConstraintSet_layout_goneMarginTop = 71;
			
			// aapt resource value: { 0x7F020001 }
			public static int[] DynamicHeightView = new int[] {
					2130837505};
			
			// aapt resource value: 0
			public const int DynamicHeightView_aspectRatio = 0;
			
			// aapt resource value: { 0x7F020001,0x7F020050,0x7F020051 }
			public static int[] ErasticSizeFrameLayout = new int[] {
					2130837505,
					2130837584,
					2130837585};
			
			// aapt resource value: 0
			public const int ErasticSizeFrameLayout_aspectRatio = 0;
			
			// aapt resource value: 1
			public const int ErasticSizeFrameLayout_maxHeightRate = 1;
			
			// aapt resource value: 2
			public const int ErasticSizeFrameLayout_maxWidthRate = 2;
			
			// aapt resource value: { 0x7F020001 }
			public static int[] FixedAspectFrameLayout = new int[] {
					2130837505};
			
			// aapt resource value: 0
			public const int FixedAspectFrameLayout_aspectRatio = 0;
			
			// aapt resource value: { 0x7F02000A,0x7F02000B,0x7F02000C,0x7F02000D,0x7F02000E,0x7F02000F }
			public static int[] FontFamily = new int[] {
					2130837514,
					2130837515,
					2130837516,
					2130837517,
					2130837518,
					2130837519};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F020009,0x7F020010,0x7F020011,0x7F020012,0x7F020056 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130837513,
					2130837520,
					2130837521,
					2130837522,
					2130837590};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			// aapt resource value: { 0x7F020013 }
			public static int[] ImageRadioButton = new int[] {
					2130837523};
			
			// aapt resource value: 0
			public const int ImageRadioButton_image = 0;
			
			// aapt resource value: { 0x10100C4 }
			public static int[] LinearConstraintLayout = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int LinearConstraintLayout_android_orientation = 0;
			
			// aapt resource value: { 0x7F020014,0x7F020046,0x7F020047,0x7F020048,0x7F020049,0x7F02004A,0x7F02004B,0x7F02004C,0x7F02004D,0x7F02004F }
			public static int[] PercentLayout_Layout = new int[] {
					2130837524,
					2130837574,
					2130837575,
					2130837576,
					2130837577,
					2130837578,
					2130837579,
					2130837580,
					2130837581,
					2130837583};
			
			// aapt resource value: 0
			public const int PercentLayout_Layout_layout_aspectRatio = 0;
			
			// aapt resource value: 1
			public const int PercentLayout_Layout_layout_heightPercent = 1;
			
			// aapt resource value: 2
			public const int PercentLayout_Layout_layout_marginBottomPercent = 2;
			
			// aapt resource value: 3
			public const int PercentLayout_Layout_layout_marginEndPercent = 3;
			
			// aapt resource value: 4
			public const int PercentLayout_Layout_layout_marginLeftPercent = 4;
			
			// aapt resource value: 5
			public const int PercentLayout_Layout_layout_marginPercent = 5;
			
			// aapt resource value: 6
			public const int PercentLayout_Layout_layout_marginRightPercent = 6;
			
			// aapt resource value: 7
			public const int PercentLayout_Layout_layout_marginStartPercent = 7;
			
			// aapt resource value: 8
			public const int PercentLayout_Layout_layout_marginTopPercent = 8;
			
			// aapt resource value: 9
			public const int PercentLayout_Layout_layout_widthPercent = 9;
			
			// aapt resource value: { 0x7F020052,0x7F020053,0x7F020054,0x7F020055 }
			public static int[] SegmentedGroup = new int[] {
					2130837586,
					2130837587,
					2130837588,
					2130837589};
			
			// aapt resource value: 0
			public const int SegmentedGroup_sc_border_width = 0;
			
			// aapt resource value: 1
			public const int SegmentedGroup_sc_checked_text_color = 1;
			
			// aapt resource value: 2
			public const int SegmentedGroup_sc_corner_radius = 2;
			
			// aapt resource value: 3
			public const int SegmentedGroup_sc_tint_color = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
