﻿// 
// This code is generated by "ParameterTemplate.tt"
// Not allowed to modify this code because your changes are deleted when in regeration.
// 

using System;

using TokyoChokoku.MarkinBox.Sketchbook.Parameters;
using TokyoChokoku.MarkinBox.Sketchbook.Properties;
using TokyoChokoku.MarkinBox.Sketchbook.Properties.Stores;
using TokyoChokoku.MarkinBox.Sketchbook.Fields;

namespace TokyoChokoku.MarkinBox.Sketchbook{

    public class TextStoreCollector : IMutableFieldVisitor<TextStore, Nil>
    {
        public TextStoreCollector ()
        {
        }

        public TextStore Visit(HorizontalText.Mutable target, Nil arg)
        {
            return target.Parameter.TextStore;
        }
           
        public TextStore Visit(YVerticalText.Mutable target, Nil arg)
        {
            return target.Parameter.TextStore;
        }
           
        public TextStore Visit(XVerticalText.Mutable target, Nil arg)
        {
            return target.Parameter.TextStore;
        }
           
        public TextStore Visit(InnerArcText.Mutable target, Nil arg)
        {
            return target.Parameter.TextStore;
        }
           
        public TextStore Visit(OuterArcText.Mutable target, Nil arg)
        {
            return target.Parameter.TextStore;
        }
           
        public TextStore Visit(QrCode.Mutable target, Nil arg)
        {
            return target.Parameter.TextStore;
        }
           
        public TextStore Visit(DataMatrix.Mutable target, Nil arg)
        {
            return target.Parameter.TextStore;
        }
           
        public TextStore Visit(Rectangle.Mutable target, Nil arg)
        {
            return null;
        }
           
        public TextStore Visit(Triangle.Mutable target, Nil arg)
        {
            return null;
        }
           
        public TextStore Visit(Circle.Mutable target, Nil arg)
        {
            return null;
        }
           
        public TextStore Visit(Line.Mutable target, Nil arg)
        {
            return null;
        }
           
        public TextStore Visit(Bypass.Mutable target, Nil arg)
        {
            return null;
        }
           
        public TextStore Visit(Ellipse.Mutable target, Nil arg)
        {
            return null;
        }
           
    }
}