﻿// 
// This code is generated by template.
// Not allowed to modify this code because your changes are deleted when in regeration.
// 

namespace TokyoChokoku.MarkinBox.Sketchbook.Validators {
    using System;
    using TokyoChokoku.MarkinBox.Sketchbook.Parameters;

    public abstract partial class MarkupTextValidator {
    
        public static MarkupTextValidator CreateOfHorizontalText (IBaseHorizontalTextParameter param) {
            return new OfHorizontalTextParameter (param);
        }


        private class OfHorizontalTextParameter : MarkupTextValidator {
            IBaseHorizontalTextParameter p;

            public OfHorizontalTextParameter (IBaseHorizontalTextParameter p) {
                this.p = p;
            }

            protected override string Text { get {
                return p.Text;
            }}
        }


        public static MarkupTextValidator CreateOfYVerticalText (IBaseYVerticalTextParameter param) {
            return new OfYVerticalTextParameter (param);
        }


        private class OfYVerticalTextParameter : MarkupTextValidator {
            IBaseYVerticalTextParameter p;

            public OfYVerticalTextParameter (IBaseYVerticalTextParameter p) {
                this.p = p;
            }

            protected override string Text { get {
                return p.Text;
            }}
        }


        public static MarkupTextValidator CreateOfXVerticalText (IBaseXVerticalTextParameter param) {
            return new OfXVerticalTextParameter (param);
        }


        private class OfXVerticalTextParameter : MarkupTextValidator {
            IBaseXVerticalTextParameter p;

            public OfXVerticalTextParameter (IBaseXVerticalTextParameter p) {
                this.p = p;
            }

            protected override string Text { get {
                return p.Text;
            }}
        }


        public static MarkupTextValidator CreateOfInnerArcText (IBaseInnerArcTextParameter param) {
            return new OfInnerArcTextParameter (param);
        }


        private class OfInnerArcTextParameter : MarkupTextValidator {
            IBaseInnerArcTextParameter p;

            public OfInnerArcTextParameter (IBaseInnerArcTextParameter p) {
                this.p = p;
            }

            protected override string Text { get {
                return p.Text;
            }}
        }


        public static MarkupTextValidator CreateOfOuterArcText (IBaseOuterArcTextParameter param) {
            return new OfOuterArcTextParameter (param);
        }


        private class OfOuterArcTextParameter : MarkupTextValidator {
            IBaseOuterArcTextParameter p;

            public OfOuterArcTextParameter (IBaseOuterArcTextParameter p) {
                this.p = p;
            }

            protected override string Text { get {
                return p.Text;
            }}
        }


        public static MarkupTextValidator CreateOfQrCode (IBaseQrCodeParameter param) {
            return new OfQrCodeParameter (param);
        }


        private class OfQrCodeParameter : MarkupTextValidator {
            IBaseQrCodeParameter p;

            public OfQrCodeParameter (IBaseQrCodeParameter p) {
                this.p = p;
            }

            protected override string Text { get {
                return p.Text;
            }}
        }


        public static MarkupTextValidator CreateOfDataMatrix (IBaseDataMatrixParameter param) {
            return new OfDataMatrixParameter (param);
        }


        private class OfDataMatrixParameter : MarkupTextValidator {
            IBaseDataMatrixParameter p;

            public OfDataMatrixParameter (IBaseDataMatrixParameter p) {
                this.p = p;
            }

            protected override string Text { get {
                return p.Text;
            }}
        }


        
    }
}