﻿﻿// 
// This code is generated by T4Template
// Not allowed to modify this code because your changes are deleted when in regeration.
// 


namespace TokyoChokoku.MarkinBox.Sketchbook.Fields {

    using TokyoChokoku.MarkinBox.Sketchbook.Parameters;
    using System.Collections.Immutable;
    using System.Collections.Generic;


    public abstract class CommonFieldVisitor <Return, Argument>
    : IFieldVisitor<Return, Argument>, IMutableFieldVisitor<Return, Argument> {

        public abstract Return Visit(HorizontalText.Constant target, Argument arg);
        public          Return Visit(HorizontalText.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


        public abstract Return Visit(YVerticalText.Constant target, Argument arg);
        public          Return Visit(YVerticalText.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


        public abstract Return Visit(XVerticalText.Constant target, Argument arg);
        public          Return Visit(XVerticalText.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


        public abstract Return Visit(InnerArcText.Constant target, Argument arg);
        public          Return Visit(InnerArcText.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


        public abstract Return Visit(OuterArcText.Constant target, Argument arg);
        public          Return Visit(OuterArcText.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


        public abstract Return Visit(QrCode.Constant target, Argument arg);
        public          Return Visit(QrCode.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


        public abstract Return Visit(DataMatrix.Constant target, Argument arg);
        public          Return Visit(DataMatrix.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


        public abstract Return Visit(Rectangle.Constant target, Argument arg);
        public          Return Visit(Rectangle.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


        public abstract Return Visit(Triangle.Constant target, Argument arg);
        public          Return Visit(Triangle.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


        public abstract Return Visit(Circle.Constant target, Argument arg);
        public          Return Visit(Circle.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


        public abstract Return Visit(Line.Constant target, Argument arg);
        public          Return Visit(Line.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


        public abstract Return Visit(Bypass.Constant target, Argument arg);
        public          Return Visit(Bypass.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


        public abstract Return Visit(Ellipse.Constant target, Argument arg);
        public          Return Visit(Ellipse.Mutable  target, Argument arg)
        {
            return Visit (target.ToConstant (), arg);
        }


    }
}
