﻿// 
// This code is generated by T4 Template.
// Not allowed to modify this code because your changes are deleted when in regeration.
// 


namespace TokyoChokoku.MarkinBox.Sketchbook.Fields {

	using TokyoChokoku.MarkinBox.Sketchbook.Parameters;
	using System.Collections.Immutable;
	using System.Collections.Generic;


	public interface IFieldVisitor <Return, Argument> {

		Return Visit(HorizontalText.Constant target, Argument arg);
		Return Visit(YVerticalText.Constant target, Argument arg);
		Return Visit(XVerticalText.Constant target, Argument arg);
		Return Visit(InnerArcText.Constant target, Argument arg);
		Return Visit(OuterArcText.Constant target, Argument arg);
		Return Visit(QrCode.Constant target, Argument arg);
		Return Visit(DataMatrix.Constant target, Argument arg);
		Return Visit(Rectangle.Constant target, Argument arg);
		Return Visit(Triangle.Constant target, Argument arg);
		Return Visit(Circle.Constant target, Argument arg);
		Return Visit(Line.Constant target, Argument arg);
		Return Visit(Bypass.Constant target, Argument arg);
		Return Visit(Ellipse.Constant target, Argument arg);
	}
}