﻿// 
// This code is generated by T4Template
// Not allowed to modify this code because your changes are deleted when in regeration.
// 


namespace TokyoChokoku.MarkinBox.Sketchbook.Fields {

	using TokyoChokoku.MarkinBox.Sketchbook.Parameters;
	using System.Collections.Immutable;
	using System.Collections.Generic;


	public interface IMutableFieldVisitor <Return, Argument> {

		Return Visit(HorizontalText.Mutable target, Argument arg);
		Return Visit(YVerticalText.Mutable target, Argument arg);
		Return Visit(XVerticalText.Mutable target, Argument arg);
		Return Visit(InnerArcText.Mutable target, Argument arg);
		Return Visit(OuterArcText.Mutable target, Argument arg);
		Return Visit(QrCode.Mutable target, Argument arg);
		Return Visit(DataMatrix.Mutable target, Argument arg);
		Return Visit(Rectangle.Mutable target, Argument arg);
		Return Visit(Triangle.Mutable target, Argument arg);
		Return Visit(Circle.Mutable target, Argument arg);
		Return Visit(Line.Mutable target, Argument arg);
		Return Visit(Bypass.Mutable target, Argument arg);
		Return Visit(Ellipse.Mutable target, Argument arg);
	}
}